set_languages("c++23")
add_requires("gtest")
add_requires("glfw")

target("opengl-resilience-tests")
    set_kind("binary")
    set_default(false)
    add_files("*.cpp")
    add_headerfiles("*.hpp")
    add_deps("shimera-opengl")
    add_packages("gtest")
    add_packages("glfw")
    
target("sfml-resilience-tests")
    set_kind("binary")
    set_default(false)
    add_files("*.cpp")
    add_headerfiles("*.hpp")
    add_deps("shimera-sfml")
    add_packages("gtest")

target("raylib-resilience-tests")
    set_kind("binary")
    set_default(false)
    add_files("*.cpp")
    add_headerfiles("*.hpp")
    add_deps("shimera-raylib")
    add_packages("gtest")
