name: CD - Build & Publish pre-releases / releases
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-Shimera:
      strategy:
        matrix:
          plateform: [ubuntu-latest, windows-latest]
          backend: [ opengl, sfml, raylib ]
          architecture: [x86, x64]
          exclude:
            - plateform: ubuntu-latest
              architecture: x86

      runs-on: ${{ matrix.plateform }}
      name: Build Shimera
      steps:
        - uses: actions/checkout@v6.0.3

        - name: Install system dependencies
          if: runner.os == 'Linux'
          run: |
            sudo apt-get update
            sudo apt-get install -y \
            build-essential cmake \
            libx11-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev \
            libgl1-mesa-dev libglu1-mesa-dev libpng-dev libfreetype6-dev \
            libxkbcommon-dev libxcb1-dev libxcb-image0-dev libxcb-keysyms1-dev \
            libxcb-shm0-dev libxcb-randr0-dev

        - name: Setup MSVC
          if: runner.os == 'Windows'
          uses: ilammy/msvc-dev-cmd@v1
          with:
            arch: ${{ matrix.architecture }}

        - name: Setup xmake
          uses: xmake-io/github-action-setup-xmake@v1
          with:
            xmake-version: latest
            actions-cache-folder: ".xmake-cache"

        - name: Extract version
          id: get_version
          shell: bash
          run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

        - name: Builds Linux
          if: runner.os == 'Linux'
          run: |
            for mode in release debug; do
              for shared in n y; do
                xmake f -y -c -m $mode --shared=$shared
                xmake build shimera-${{ matrix.backend }}
              done
            done

        - name: Builds Windows
          if: runner.os == 'Windows'
          shell: powershell
          run: |
            foreach ($mode in @("release", "debug")) {
              foreach ($shared in @("n", "y")) {
                xmake f -y -c -m $mode --shared=$shared -a ${{ matrix.architecture }}
                xmake build shimera-${{ matrix.backend }}
              }
            }

        - name: Tar Linux builds
          if: runner.os == 'Linux'
          run: |
            mkdir -p shimera-${{ env.version }}/lib shimera-${{ env.version }}/include/shimera
            mv build/linux/x86_64/{release,debug}/*.{so,a} shimera-${{ env.version }}/lib/
            mv include shimera-${{ env.version }}/include/shimera
            tar -cvf shimera-${{ env.version }}-${{ matrix.backend }}-linux-${{ matrix.architecture }}.tar shimera-${{ env.version }}

        - name: Zip Windows builds
          if: runner.os == 'Windows'
          shell: powershell
          run: |
            New-Item -ItemType Directory -Force -Path shimera-${{ env.version }}\lib, shimera-${{ env.version }}\bin, shimera-${{ env.version }}\include\shimera
            Move-Item build\windows\${{ matrix.architecture }}\release\*.lib, build\windows\${{ matrix.architecture }}\debug\*.lib shimera-${{ env.version }}\lib\
            Move-Item build\windows\${{ matrix.architecture }}\release\*.dll, build\windows\${{ matrix.architecture }}\debug\*.dll shimera-${{ env.version }}\bin\
            Get-ChildItem build\windows\${{ matrix.architecture }}\release\*.pdb, build\windows\${{ matrix.architecture }}\debug\*.pdb | Where-Object { $_.Name -notlike "compile.*" } | Move-Item -Destination shimera-${{ env.version }}\bin\
            Move-Item include shimera-${{ env.version }}\include\shimera
            Compress-Archive -Path shimera-${{ env.version }} -DestinationPath shimera-${{ env.version }}-${{ matrix.backend }}-windows-${{ matrix.architecture }}.zip

        - name: Upload Linux artifact
          if: runner.os == 'Linux'
          uses: actions/upload-artifact@v7
          with:
            name: shimera-build-linux-${{ matrix.backend }}
            path: shimera-${{ env.version }}-${{ matrix.backend }}-linux-${{ matrix.architecture }}.tar

        - name: Upload Windows artifact
          if: runner.os == 'Windows'
          uses: actions/upload-artifact@v7
          with:
            name: shimera-build-windows-${{ matrix.backend }}-${{ matrix.architecture }}
            path: shimera-${{ env.version }}-${{ matrix.backend }}-windows-${{ matrix.architecture }}.zip

  publish:
    needs: [build-Shimera]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux builds
        uses: actions/download-artifact@v8
        with:
          pattern: shimera-build-linux-*
          merge-multiple: true

      - name: Download Windows builds
        uses: actions/download-artifact@v8
        with:
          pattern: shimera-build-windows-*
          merge-multiple: true

      - name: Check if prerelease
        id: check_prerelease
        run: |
          if [[ "${{ github.ref_name }}" == *"-"* ]]; then
            echo "prerelease=true" >> $GITHUB_ENV
          else
            echo "prerelease=false" >> $GITHUB_ENV
          fi

      - name: Extract version
        id: get_version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          name: Shimera ${{ env.version }}
          prerelease: ${{ env.prerelease }}
          files: |
            *.tar
            *.zip

  check-tag:
    needs: [publish]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3

      - name: Extract tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Delete tag
        run: |
          git fetch --tags
          git tag -d $TAG_NAME
          git push origin --delete $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}