name: CI / Windows (xmake)
on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - fix/75-ci-and-docs

jobs:
    Build-Shimera:
      name: Build Shimera
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v4

        - name: Setup xmake
          uses: xmake-io/github-action-setup-xmake@v1
          with:
            xmake-version: latest
            actions-cache-folder: ".xmake-cache"

        - name: Build Shimera
          run: xmake -y

        - name: Upload Shimera build
          uses: actions/upload-artifact@v4
          with:
            name: shimera-build
            path: build/
    
    Build-Sfml:
      name: Build Sfml example
      runs-on: windows-latest
      needs: Build-Shimera
      steps:
        - uses: actions/checkout@v4

        - name: Download Shimera build
          uses: actions/download-artifact@v4
          with:
            name: shimera-build
            path: build/

        - name: Setup xmake
          uses: xmake-io/github-action-setup-xmake@v1
          with:
            xmake-version: latest
            actions-cache-folder: '.xmake-cache'

        - name: Build Sfml
          run: xmake -y
          working-directory: ./examples/sfml

    Build-OpenGL:
      name: Build OpenGL example
      runs-on: windows-latest
      needs: Build-Shimera
      steps:
        - uses: actions/checkout@v4

        - name: Download Shimera build
          uses: actions/download-artifact@v4
          with:
            name: shimera-build
            path: build/

        - name: Setup xmake
          uses: xmake-io/github-action-setup-xmake@v1
          with:
            xmake-version: latest
            actions-cache-folder: '.xmake-cache'
          
        - name: Build OpenGl
          run: xmake -y
          working-directory: ./examples/opengl

    Build-Sdl:
      name: Build Sdl example
      runs-on: windows-latest
      needs: Build-Shimera
      steps:
        - uses: actions/checkout@v4

        - name: Download Shimera build
          uses: actions/download-artifact@v4
          with:
            name: shimera-build
            path: build/

        - name: Setup xmake
          uses: xmake-io/github-action-setup-xmake@v1
          with:
            xmake-version: latest
            actions-cache-folder: '.xmake-cache'

        - name: Build Sdl
          run: xmake -y
          working-directory: ./examples/sdl
