name: CI / Linux (xmake)
on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - task/46-create-memory-workflow

jobs:
    ci-linux:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install system dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y \
            build-essential \
            cmake \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            libxinerama-dev \
            libxcursor-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libpng-dev \
            libfreetype6-dev

        - name: Setup xmake
          uses: xmake-io/github-action-setup-xmake@v1
          with:
            xmake-version: latest

        - name: Build Sfml
          run: xmake -y
          working-directory: ./example/sfml

        - name: Build OpenGl
          run: xmake -y
          working-directory: ./example/opengl

        - name: Build Sdl
          run: xmake -y
          working-directory: ./example/sdl
          