name: CI / Linux (xmake)
on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - task/46-create-memory-workflow

jobs:
    Setup-dependencies:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Install system dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y \
            build-essential cmake \
            libx11-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev \
            libgl1-mesa-dev libglu1-mesa-dev libpng-dev libfreetype6-dev \
            libxkbcommon-dev libxcb1-dev libxcb-image0-dev libxcb-keysyms1-dev \
            libxcb-shm0-dev libxcb-randr0-dev
    
    Build-Sfml:
      runs-on: ubuntu-latest
      needs: Setup-dependencies
      steps:
        - uses: actions/checkout@v4

        - name: Setup xmake
          uses: xmake-io/github-action-setup-xmake@v1
          with:
            xmake-version: latest
            actions-cache-folder: '.xmake-cache'

        - name: Build Sfml
          run: xmake -y
          working-directory: ./example/sfml

    Build-OpenGL:
        runs-on: ubuntu-latest
        needs: Setup-dependencies
        steps:
          - uses: actions/checkout@v4

          - name: Setup xmake
            uses: xmake-io/github-action-setup-xmake@v1
            with:
              xmake-version: latest
              actions-cache-folder: '.xmake-cache'
          
          - name: Build OpenGl
            run: xmake -y
            working-directory: ./example/opengl

    Build-Sdl:
        runs-on: ubuntu-latest
        needs: Setup-dependencies
        steps:
          - uses: actions/checkout@v4

          - name: Setup xmake
            uses: xmake-io/github-action-setup-xmake@v1
            with:
              xmake-version: latest
              actions-cache-folder: '.xmake-cache'

          - name: Build Sdl
            run: xmake -y
            working-directory: ./example/sdl
