name: Update Submodules

permissions:
  contents: write

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  sync:
    name: Update Submodules
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          submodules: recursive

      - name: Update submodules
        run: |
          git submodule update --remote --recursive

      - name: Commit update
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'github-actions@noreply.github.com'
          git add .
          git commit -m "chore(ci): auto-update submodules to latest" || exit 0
          git push
